import Link from 'next/link';
import {allocations,population,totals} from '../../src/residential-plan.js';
import {districts} from '../../src/settlement-plan.js';
import Plan from './plan';
import './residential.css';
export const metadata={title:'Residential side terraces · Stanford Torus'};
const n=v=>v.toLocaleString('en',{maximumFractionDigits:0});
export default function ResidentialPage(){return <main className="residential-page">
<nav><Link href="/layout/">Six-sector master plan</Link><a href={`/oneillsim/?theta=${districts[0].center*180/Math.PI}&z=0&mode=planner&height=120&pitch=-60&yaw=0`}>District in 3D ↗</a><Link href="/agriculture/">Agriculture</Link><Link href="/assets/">Assets</Link></nav>
<header><p className="eyebrow">DESIGN NOTE 01 · REVISION 2</p><h1>Housing rises around a garden basin.</h1><p>District A houses 3,333 people in a {(districts[0].end*180/Math.PI).toFixed(2)}° sector. The first sketch’s equal-sector shortfall has been resolved by the new 430:240 land split; the cross-section now uses the bottom arc instead of placing everything at the tube diameter.</p></header>
<Plan/>
<section><h2>Cross-section decisions</h2><p>The central park and inner housing shelf sit at −48 m. Middle shelves sit at −32 m, and upper side shelves at −12 m. Housing steps up both sides: sixteen five-story blocks in the basin, sixteen four-story blocks on the middle shelves, and sixteen two-story blocks along the outer shelves. Each story is 3 m high. The occupied floor area remains <strong>{n(totals('housing').floor)} m²</strong>, or 37 m²/person.</p><p>This lowers the central garden and increases its overhead clearance to the top of the 65 m-radius tube to approximately 113 m. That is geometric clearance, before lighting or other overhead infrastructure. All shelf slabs and building envelopes fit within the tube; higher shelves overlap small parts of lower housing in projection. The 24 × 24 m spoke landing is centered on the basin, with a tall marker for its axis.</p><p>The lower service deck is at −61.5 m and contains shops, offices, workshops, storage, recreation and miscellaneous space. These are tight conceptual envelopes, not construction-ready designs. Access between residential shelves, structural depth, ramps, lifts, drainage and egress remain unresolved. The deck selector can be used to inspect and enter a shelf.</p></section>
<section><h2>Separate space accounts</h2><div className="table-scroll"><table><thead><tr><th>Use</th><th>Target m²/person</th><th>Placed usable m²</th></tr></thead><tbody>{[['housing','Indoor housing',37,'floor'],['terrace','Shared residential exterior/access reserve',12,'footprint'],['park','Public park',10,'footprint'],['circulation','Public circulation reserve',12,'footprint']].map(([key,label,target,field])=><tr key={key}><th>{label}</th><td>{target}</td><td>{n(totals(key)[field])}</td></tr>)}</tbody></table></div><p>Exterior/access and circulation are currently non-overlapping reserved parcels on the shelves. They are not yet a connected path network or assigned private terraces. Tree canopies decorate the park and do not add area credit. The landing is excluded from these four totals. This avoids counting a park, access terrace and upper floor as the same usable space.</p><p>The sector has {n(districts[0].projectedArea)} m² of projected ground allocation. Usable deck areas can overlap in projection; their sum is a different quantity. Sector area now exceeds the study’s 430,000 ÷ 3 m² community share because the available ground surplus is distributed proportionally.</p></section>
<section><h2>Reference allocation ledger</h2><p><Link href="/study/#sp413-s00708">Table 3-2</Link>, checked against <a href="https://ntrs.nasa.gov/api/citations/19770014162/downloads/19770014162.pdf#page=43">PDF page 43</a>. Printed rounding is preserved. Residential 49 m²/person means 37 indoors plus 12 exterior/access; the four-level stacking factor is an overall planning assumption.</p><div className="table-scroll"><table><thead><tr><th>Use</th><th>Surface m²/person</th><th>Levels</th><th>Projected m²/person</th><th>Height m</th></tr></thead><tbody>{allocations.map(a=><tr key={a.key}><th>{a.name}</th><td>{a.surface}</td><td>{a.levels}</td><td>{a.projected}</td><td>{a.height}</td></tr>)}</tbody></table></div><p>The park’s 50 m is desired open overhead clearance, not a building height. Mechanical allocations are not all placed here; farm A contains the first water-treatment share.</p></section>
<section><h2>Source versus design decision</h2><ul><li><Link href="/study/#sp413-s02265">Chapter 5</Link> describes housing terraced up the walls and commerce below the central plain. Lowering the central garden to −48 m is our current interpretation, not a dimension taken from the drawing.</li><li><Link href="/study/#sp413-s02268">The housing description</Link> includes one-/two-level homes and four-/five-story groups. Our block counts, footprints and locations are design choices.</li><li><Link href="/study/#sp413-s02289">Table 5-1</Link> provides the 430,000:240,000 m² allocation. The approximately 77°:43° sectors are our explicit implementation.</li><li><Link href="/study/#sp413-s02293">The roughly 400 m walk to a spoke</Link> remains unverified: the wider sector has a half-length exceeding 550 m before cross-sectional walking. Centering a landing does not by itself meet that target.</li></ul></section>
<section><h2>How this is recorded</h2><p>The <Link href="/layout/">master plan</Link> stores each district’s start/end angles and population. Every generated parcel records its district ID, fraction along the district (u), tube-axis position (z), terrace ID, elevation, dimensions and use. The world saves the sector plan and deck surfaces with placed assets. This keeps a parcel’s identity separate from its geometry, so later revisions can resize sectors and reposition shelves deliberately. Regeneration replaces the generated layout; manual placement is not a live parametric constraint solver.</p></section>
</main>}
