import Link from 'next/link';
import {allocations,blocks,population,length,totals} from '../../src/residential-plan.js';
import Plan from './plan';
import './residential.css';
export const metadata={title:'Residential district A · Stanford Torus'};
const number=n=>n.toLocaleString('en',{maximumFractionDigits:0});
const source=id=>`/study/#${id}`;
export default function ResidentialPage(){return <main className="residential-page">
<nav><a href="/oneillsim/?theta=30&z=0&mode=planner&height=180&pitch=-89&yaw=0">Open district in 3D ↗</a><Link href="/assets/">Asset library</Link><Link href="/agriculture/">Agricultural terraces</Link><Link href="/study/">Study</Link></nav>
<header><p className="eyebrow">DESIGN NOTE 01 · WORKING BLOCKOUT</p><h1>One neighborhood, 3,333 residents.</h1><p>District A is the first of three residential areas for a 10,000-person settlement. Colored volumes establish scale and land use before we design individual buildings.</p></header>
<Plan/>
<section><h2>What is placed</h2><p>Forty multi-dwelling housing blocks: four at two stories, twelve at four, and twenty-four at five. Their combined occupied floor area is <strong>{number(totals('housing').floor)} m²</strong>, exactly 37 m² for each of 3,333 residents. A block is a group of homes, not a single house. Every block has a 32 m frontage, a {number(totals('housing').footprint/40/32)} m depth and 3 m floor-to-floor height. Floor plates are conceptual gross capacity; apartment partitions, cores and dwelling counts are not designed yet.</p>
<p>Two three-story school wings and two clinic wings flank a central civic cluster with four assembly halls. A continuous linear park supplies {number(totals('park').footprint)} m²; paths supply {number(totals('circulation').footprint)} m². Fifty-six green cubes stand in for fruit-tree canopies. These sit within the park and do not add to its area. Shops, offices, workshops, storage, recreation, the remaining assembly space and miscellaneous uses have reserved volumes below the deck. Switch the plan above to inspect them; they are naturally hidden by the ground in the simulation.</p>
<p>The model replaces only the first 60° sector using the latest server world as the starting point. The residential generator preserves the other five sectors. The adjacent agricultural sector now has its own terraced blockout; the remaining four sectors retain their saved contents.</p></section>
<section className="constraint"><h2>The area problem we need to solve</h2><p>Our equal sixth of the current 830 m-radius, 130 m-wide ground sheet measures {number(length)} × 130 m, or <strong>{number(length*130)} m²</strong>. Chapter 5 assigns 43 m²/person to community life: <strong>{number(43*population)} m²</strong> here. That is a <strong>{number(43*population-length*130)} m² shortfall</strong> against this simplified ground sheet.</p><p>This sketch meets the indoor housing, public park and circulation quantities, but it is <strong>not a complete fit to the study</strong>. Residential exterior/access space adds another {number(12*population)} m² of usable terrace area that is not yet modeled. Below-deck services overlap the ground projection; they do not magically create additional ground area. Wider residential sectors, sidewall terraces and multi-level decks need a separate geometry decision. Mechanical plant is still a settlement-wide reservation, not placed here.</p><p>Table 3-2 uses rounded projected values: 49 ÷ 4 is 12.25, not the printed 12; storage 5 ÷ 4 is 1.25, not the printed 1. The table below preserves those published values. Our generated boxes use surface area divided by levels instead of silently inheriting the rounding.</p></section>
<section><h2>Source allocation ledger</h2><p>Visually checked against <a href="https://ntrs.nasa.gov/api/citations/19770014162/downloads/19770014162.pdf#page=43">NASA SP-413, Table 3-2, printed page 26 / PDF page 43</a>. <Link href={source('sp413-s00708')}>Open the transcribed table</Link>. Surface area includes all stacked levels; projected area is its plan allocation. The source calls these approximations for mass and enclosure planning.</p>
<div className="table-scroll"><table><thead><tr><th>Use</th><th>Surface m²/person</th><th>Levels</th><th>Projected m²/person</th><th>Height per level m</th><th>District surface m²</th><th>District projected m²</th></tr></thead><tbody>{allocations.map(a=><tr key={a.key}><th>{a.name}</th><td>{a.surface}</td><td>{a.levels}</td><td>{a.projected}</td><td>{a.height}</td><td>{number(a.surface*population)}</td><td>{number(a.projected*population)}</td></tr>)}</tbody></table></div><p>The park’s 50 m entry is open overhead clearance, not a 50 m building. Mechanical rows are listed for context and excluded from the placed district. Agriculture is outside this residential scope.</p></section>
<section><h2>How the references shaped the plan</h2><ul>
<li><Link href={source('sp413-s00911')}>Chapter 3, Appendix B: residences</Link> gives 148 m² for four people, or 37 m²/person indoors, plus 12 m²/person exterior/access. Four levels are a planning stacking factor, not an instruction for every building.</li>
<li><Link href={source('sp413-s02268')}>Chapter 5: residential architecture</Link> describes one- and two-level homes, four- and five-story groups, and terraces up the curved walls. The 2/4/5-story mix here is our choice; the study supplies no percentages or footprint for each size.</li>
<li><Link href={source('sp413-s00940')}>Open space</Link> is 10 m²/person. <Link href={source('sp413-s02373')}>Fruit trees belong in residential parks</Link>. The linear park and tree spacing are authored choices, not a traced NASA plan.</li>
<li><Link href={source('sp413-s00958')}>Circulation</Link> allows a 15 m major right of way and 12 m²/person overall. We use two edge corridors, two 7 m promenades and short connecting paths. Transit stops, crossings through the park and spoke entry still need design.</li>
<li><Link href={source('sp413-s02265')}>Below-deck commerce and services</Link> free up the central plain. The lower deck at −16 m is a provisional placement, with no lifts, access routes, structure or fire compartments designed yet.</li>
<li><Link href={source('sp413-s00930')}>The hospital rationale</Link> proposes 50 beds for the whole colony. These two clinic volumes represent this district’s floor-area share, not two hospitals or a verified bed capacity.</li>
<li><Link href={source('sp413-s02344')}>Three residential areas alternate with three agricultural areas</Link>. Our population split is 3,333 / 3,333 / 3,334. Equal 60° sectors are the current simulator convention, not a verified land-allocation solution.</li>
<li><Link href={source('sp413-s02276')}>Placement requirements</Link> include access to spokes, mass balance, noise isolation, fire prevention and pedestrian travel. The report’s roughly <Link href={source('sp413-s02293')}>400 m maximum walk to an elevator</Link> remains a target to test against a designed entrance and actual walking routes.</li>
</ul></section>
<section><h2>Next landscape decisions</h2><p>First, choose whether to widen residential sectors or add sidewall terrace decks. Then locate the spoke entrance, break the linear park into connected gardens and squares, and refine the housing clusters around those routes. Add street-level shops and community kitchens once their relationship to the lower-deck service allocation is settled. This blockout intentionally exposes the unresolved area budget before detailed modeling.</p></section>
</main>}
