import Link from 'next/link';
import {districts} from '../../src/settlement-plan.js';
import '../residential/residential.css';
export const metadata={title:'Six-sector master plan · Stanford Torus'};
const n=v=>v.toLocaleString('en',{maximumFractionDigits:0});
export default function LayoutPage(){return <main className="residential-page"><nav><Link href="/residential/">Residential terraces</Link><Link href="/agriculture/">Agriculture</Link><a href="/oneillsim/">Simulation</a></nav><header><p className="eyebrow">MASTER PLAN · REVISION 1</p><h1>Three neighborhoods, three farms.</h1><p>Each 120° pair uses the study’s 430:240 residential-to-agricultural/mechanical area ratio. The full modeled ground is divided proportionally, including its small surplus above the study’s 670,000 m² requirement.</p></header>
<svg viewBox="-150 -150 300 300" style={{width:500,maxWidth:'100%'}} aria-label="Six alternating sectors and centered spoke landings">{districts.map(d=>{const point=(a,r)=>`${r*Math.cos(a)},${-r*Math.sin(a)}`;return <g key={d.id}><path d={`M ${point(d.start,110)} A 110 110 0 0 0 ${point(d.end,110)} L ${point(d.end,75)} A 75 75 0 0 1 ${point(d.start,75)} Z`} fill={d.kind==='residential'?'#d9ad73':'#81a855'} stroke="white"/><line x1="0" y1="0" x2={93*Math.cos(d.center)} y2={-93*Math.sin(d.center)} stroke="#b584b9" strokeWidth="1"/><circle cx={93*Math.cos(d.center)} cy={-93*Math.sin(d.center)} r="4" fill="#9d589b"/><text x={132*Math.cos(d.center)} y={-132*Math.sin(d.center)} textAnchor="middle" fontSize="8">{d.name}</text></g>})}<circle r="8" fill="#647b80"/></svg>
<p>Violet points mark 24 × 24 m placeholder landings at each district’s angular midpoint and z = 0. The lines indicate spoke directions, not engineered spoke structures. Only residential A and farm A contain detailed blockouts; B and C retain simple land-use ground and their landing markers.</p>
<div className="table-scroll"><table><thead><tr><th>District</th><th>Start °</th><th>End °</th><th>Width °</th><th>Projected m²</th><th>Spoke center °</th></tr></thead><tbody>{districts.map(d=><tr key={d.id}><th><a href={`/oneillsim/?theta=${d.center*180/Math.PI}&z=0&mode=planner&height=160&pitch=-89&yaw=0`}>{d.name} ↗</a></th><td>{(d.start*180/Math.PI).toFixed(2)}</td><td>{(d.end*180/Math.PI).toFixed(2)}</td><td>{((d.end-d.start)*180/Math.PI).toFixed(2)}</td><td>{n(d.projectedArea)}</td><td>{(d.center*180/Math.PI).toFixed(2)}</td></tr>)}</tbody></table></div>
<h2>Evidence and assumptions</h2><p><Link href="/study/#sp413-s02289">Table 5-1</Link> lists 430,000 m² of projected community area, 240,000 m² for agriculture/processing/mechanical uses, and 678,000 m² available. Our 830 m radius and 130 m width yield {n(2*Math.PI*830*130)} m². Sector widths are an allocation decision, not a claim that the study’s plan drawing specifies those angles. Within each repeating pair, spoke centers remain 60° apart.</p><h2>Coordinate record</h2><p>Each district has a stable ID and angular bounds. A parcel uses u = 0…1 along that district, z in metres across the tube, and a deck ID/elevation measured inward from the 830 m reference radius. Physical deck length is angular width × (830 − elevation), so lower decks are longer. Building footprint, floor count and use remain explicit and separate from the district’s projected land budget. The world stores this master plan, deck topology and asset attachments together.</p></main>}
