import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {chromium} from 'playwright';
import {candidateWorld} from '../scripts/place-completed-models.mjs';
import {completedModels} from '../src/completed-models.js';
import {completedModelPlacements} from '../src/model-placement.js';
const base=(process.env.ONEILLSIM_TEST_URL||'http://127.0.0.1:3200/oneillsim/').replace(/\/?$/,'/'),target=new URL(base),candidate=process.env.MODEL_PLACEMENT_CANDIDATE==='1';
test('all 47 saved placements load in proper frames, share atlases, register only interior collision and roundtrip without writes',{timeout:240000},async()=>{
 const local=JSON.parse(await fs.readFile('world.json','utf8')),expected=candidate?candidateWorld(local).next:local,planned=completedModelPlacements(expected);
 const browser=await chromium.launch({executablePath:'/opt/oneillsim-renderer/chromium-1208/chrome-linux64/chrome',args:['--no-sandbox','--disable-dev-shm-usage']});
 try{
  const page=await browser.newPage({viewport:{width:640,height:400}}),errors=[],writes=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',async r=>{if(!['GET','HEAD'].includes(r.request().method())){writes.push(r.request().url());await r.abort();return;}const u=new URL(r.request().url());if(candidate&&u.origin===target.origin&&u.pathname.endsWith('/world.json')){const response=await r.fetch();await r.fulfill({response,json:expected});return;}await r.continue();});
  await page.goto(base+'?capture=1&theta=151&z=10&mode=planner&height=45&yaw=-90&pitch=-55',{waitUntil:'domcontentloaded',timeout:30000});await page.waitForFunction(()=>window.__oneillSimReady||window.__oneillSimError,null,{timeout:120000});
  const result=await page.evaluate(async({planned,models})=>{
   if(window.__oneillSimError)throw Error(window.__oneillSimError);window.requestAnimationFrame=()=>0;
   const T=await import('three'),{scene,renderer,camera,habitatGroup}=await import('./src/scene.js'),{editorState,exportWorldState}=await import('./src/editor/state.js'),{characterColliders}=await import('./src/physics/collider-world.js'),{getAsset}=await import('./src/editor/loader.js');
   habitatGroup.updateWorldMatrix(true,true);const inverse=habitatGroup.matrixWorld.clone().invert(),objects=new Map(habitatGroup.children.filter(o=>o.userData.assetId).map(o=>[o.userData.assetId,o]));const rows=[],kitMaterials=new Map(),kitMaps=new Map();
   for(const p of planned){const o=objects.get(p.id);if(!o)throw Error('Missing object '+p.id);const m=models.find(m=>m.id===p.type),meshes=[],protos=[];o.traverse(c=>{if(c.isMesh)meshes.push(c)});getAsset(p.type).traverse(c=>{if(c.isMesh)protos.push(c)});if(meshes.length!==1)throw Error('Unexpected meshes '+p.id);const mesh=meshes[0];if(kitMaterials.has(m.materialKit)&&kitMaterials.get(m.materialKit)!==mesh.material)throw Error('Incompatible/unpooled kit '+p.id);kitMaterials.set(m.materialKit,mesh.material);kitMaps.set(m.materialKit,mesh.material.map);
    let maximumTubeDistance=0,minimumTubeDistance=Infinity;const matrix=new T.Matrix4(),v=new T.Vector3();o.traverse(c=>{if(!c.isMesh)return;matrix.multiplyMatrices(inverse,c.matrixWorld);for(let i=0;i<c.geometry.attributes.position.count;i++){v.fromBufferAttribute(c.geometry.attributes.position,i).applyMatrix4(matrix);const distance=Math.hypot(Math.hypot(v.x,v.y)-830,v.z);maximumTubeDistance=Math.max(maximumTubeDistance,distance);minimumTubeDistance=Math.min(minimumTubeDistance,distance);}});
    rows.push({id:p.id,type:p.type,exterior:!!p.surface.worldTransform,position:o.position.toArray(),quaternion:o.quaternion.toArray(),scale:o.scale.toArray(),colliders:characterColliders.colliders.get(p.id)?.length||0,textureDecoded:!!mesh.material.map?.image?.width,borrowedGeometry:mesh.geometry===protos[0].geometry,borrowedMaterial:mesh.material===protos[0].material,maximumTubeDistance,minimumTubeDistance});
   }
   const {CharacterController}=await import('./src/physics/character-controller.js'),{inTerraceSector}=await import('./src/terrace-surfaces.js');
   const routes=[['completed-model-markets',[0,.001,6.7],[0,0,-4.5]],['completed-model-restaurants',[0,.001,6],[0,0,0]],['completed-model-factories',[6.3,.001,7.5],[6.3,0,0]],['completed-model-greenhouses',[0,.001,4.7],[0,.08,-3]],['completed-model-animal-housing',[0,.001,4.7],[0,.08,-3]]];
   const stairManifest=await fetch('assets/ultimate-buildings/TorusTransport_StairsRampA.asset.json').then(r=>r.json());for(const r of stairManifest.collisionIntent.routes)routes.push(['completed-model-stairs-ramps',r.startMeters,r.endMeters]);
   const traversals=[];for(const [id,start,end] of routes){const o=objects.get(id),localInverse=o.matrix.clone().invert(),controller=new CharacterController(characterColliders,{groundExists:theta=>!inTerraceSector(theta)});controller.teleport(new T.Vector3(...start).divideScalar(4).applyMatrix4(o.matrix));for(let i=0;i<30;i++)controller.tick(new T.Vector3());const direction=new T.Vector3(0,0,-1).transformDirection(o.matrix);let ticks=0;for(;ticks<300;ticks++){const local=controller.position.clone().applyMatrix4(localInverse).multiplyScalar(4);if(local.z<=end[2])break;controller.tick(direction);}for(let i=0;i<60;i++)controller.tick(new T.Vector3());const local=controller.position.clone().applyMatrix4(localInverse).multiplyScalar(4);traversals.push({id,ticks,position:local.toArray(),expected:end,grounded:controller.grounded,clear:controller.clear()});}
   const {placeAsset,removeAsset}=await import('./src/editor/placement.js'),hub=objects.get('completed-model-central-hub'),hubMesh=hub.children.find(c=>c.isMesh);let disposed=0;hubMesh.geometry.addEventListener('dispose',()=>disposed++);hubMesh.material.addEventListener('dispose',()=>disposed++);const surface=structuredClone(planned.find(p=>p.id==='completed-model-central-hub').surface),temp=await placeAsset('TorusStructure_HubA',1,7,4,.9,surface),clone=habitatGroup.children.find(o=>o.userData.assetId===temp);const lifecycle={position:clone.position.toArray(),quaternion:clone.quaternion.toArray(),collider:characterColliders.colliders.has(temp),surface:editorState.placedAssets.find(a=>a.id===temp).surface,removed:removeAsset(temp)};lifecycle.disposed=disposed;lifecycle.restored=!habitatGroup.children.includes(clone)&&!editorState.placedAssets.some(a=>a.id===temp);
   const exported=exportWorldState(),saved=await fetch('world.json').then(r=>r.json());renderer.render(scene,camera);
   return {rows,traversals,lifecycle,loadedIds:editorState.placedAssets.map(a=>a.id),sceneIds:[...objects.keys()],saved,exported,kitMaterials:kitMaterials.size,kitMaps:new Set(kitMaps.values()).size,atlasRequests:[...new Set(models.map(m=>m.textureAtlas))].map(name=>({name,count:performance.getEntriesByType('resource').filter(r=>r.name.includes('/'+name)).length})),colliders:characterColliders.colliders.size,triangles:characterColliders.triangleCount,render:renderer.info.render};
  },{planned,models:completedModels});
  assert.equal(result.rows.length,47);assert.deepEqual(result.loadedIds,expected.assets.map(a=>a[0]));assert.equal(result.sceneIds.length,expected.assets.length);assert.deepEqual(result.saved,expected);assert.equal(result.kitMaterials,7);assert.equal(result.kitMaps,7);
  for(const r of result.rows){assert.deepEqual(r.scale,[4,4,4]);assert.equal(r.textureDecoded,true);assert.equal(r.borrowedGeometry,true);assert.equal(r.borrowedMaterial,true);const p=planned.find(p=>p.id===r.id);if(r.exterior){assert.equal(r.colliders,0);assert.ok(r.minimumTubeDistance>65);for(let i=0;i<3;i++)assert.ok(Math.abs(r.position[i]-p.surface.worldTransform.position[i])<1e-8);for(let i=0;i<4;i++)assert.ok(Math.abs(r.quaternion[i]-p.surface.worldTransform.quaternion[i])<1e-8);}else{assert.ok(r.colliders>0);assert.ok(r.maximumTubeDistance<65,r.id+' exceeds tube '+r.maximumTubeDistance);}const a=result.exported.assets.find(a=>a[0]===r.id);assert.ok(a);assert.equal(result.exported.assetTypes[a[1]],p.type);assert.deepEqual(a[7],p.surface);}
  const hub=planned.find(p=>p.id==='completed-model-central-hub');assert.deepEqual(result.lifecycle.position,hub.surface.worldTransform.position);assert.deepEqual(result.lifecycle.quaternion,hub.surface.worldTransform.quaternion);assert.deepEqual(result.lifecycle.surface,hub.surface);assert.equal(result.lifecycle.collider,false);assert.equal(result.lifecycle.removed,true);assert.equal(result.lifecycle.restored,true);assert.equal(result.lifecycle.disposed,0);
  for(const r of result.traversals){assert.ok(r.ticks<300,JSON.stringify(r));assert.ok(Math.abs(r.position[1]-r.expected[1])<.15,JSON.stringify(r));assert.equal(r.grounded,true,JSON.stringify(r));assert.equal(r.clear,true,JSON.stringify(r));}assert.equal(result.traversals.length,7);
  for(const atlas of result.atlasRequests)assert.equal(atlas.count,1,atlas.name);assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);
  const scratch=process.env.TMPDIR||path.join(os.homedir(),'.hermes/cache/scratch');
  await page.evaluate(async()=>{const T=await import('three'),{scene,renderer,habitatGroup}=await import('./src/scene.js');const a=142*Math.PI/180,c=new T.PerspectiveCamera(55,640/400,.05,5000);c.position.copy(habitatGroup.localToWorld(new T.Vector3(795*Math.cos(a),795*Math.sin(a),65)));c.up.copy(new T.Vector3(-Math.cos(a),-Math.sin(a),0).transformDirection(habitatGroup.matrixWorld));c.lookAt(habitatGroup.localToWorld(new T.Vector3(830*Math.cos(a),830*Math.sin(a),0)));renderer.render(scene,c);});await page.screenshot({path:path.join(scratch,'completed-model-placement-neighborhood.png')});
  await page.evaluate(async()=>{const T=await import('three'),{scene,renderer,habitatGroup}=await import('./src/scene.js'),{editorState}=await import('./src/editor/state.js');const p=editorState.placedAssets.find(a=>a.id==='completed-model-greenhouses'),a=p.theta-.003,r=830-p.surface.anchorHeight,c=new T.PerspectiveCamera(68,640/400,.05,5000);c.position.copy(habitatGroup.localToWorld(new T.Vector3((r-1.65)*Math.cos(a),(r-1.65)*Math.sin(a),57)));c.up.copy(new T.Vector3(-Math.cos(a),-Math.sin(a),0).transformDirection(habitatGroup.matrixWorld));c.lookAt(habitatGroup.localToWorld(new T.Vector3((r-1.1)*Math.cos(a),(r-1.1)*Math.sin(a),36)));renderer.render(scene,c);});await page.screenshot({path:path.join(scratch,'completed-model-placement-farm.png')});
  await page.evaluate(async()=>{const T=await import('three'),{scene,renderer,habitatGroup}=await import('./src/scene.js');const c=new T.PerspectiveCamera(55,640/400,.05,5000);c.position.copy(habitatGroup.localToWorld(new T.Vector3(250,-260,260)));c.up.set(0,0,1);c.lookAt(habitatGroup.localToWorld(new T.Vector3(20,0,70)));renderer.render(scene,c);});await page.screenshot({path:path.join(scratch,'completed-model-placement-exterior.png')});
  await fs.writeFile(path.join(scratch,'completed-model-placement-profile.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({modelPlacement:{candidate,total:expected.assets.length,newModels:result.rows.length,interior:result.rows.filter(r=>!r.exterior).length,exterior:result.rows.filter(r=>r.exterior).length,colliders:result.colliders,triangles:result.triangles,atlases:result.atlasRequests}}));
 }finally{await browser.close();}
});
