import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {chromium} from 'playwright';
import {buildSettlementPlan} from '../src/settlement-world.js';
import {settlementCandidate} from '../scripts/apply-settlement-design.mjs';
const base=(process.env.ONEILLSIM_TEST_URL||'http://127.0.0.1:3200/oneillsim/').replace(/\/?$/,'/'),candidate=process.env.SETTLEMENT_CANDIDATE==='1';
test('complete authored settlement loads, persists metadata and inventory, renders named places and accepts real human movement without world writes',{timeout:360000},async()=>{
 const local=JSON.parse(await fs.readFile('world.json','utf8')),plan=await buildSettlementPlan(),expected=candidate?settlementCandidate(local,plan).next:local;
 assert.equal(expected.settlementDesign?.version,1,'Full design not applied; use SETTLEMENT_CANDIDATE=1 for read-only preview');
 const scratch=process.env.TMPDIR||path.join(os.homedir(),'.hermes/cache/scratch'),browser=await chromium.launch({executablePath:'/opt/oneillsim-renderer/chromium-1208/chrome-linux64/chrome',args:['--no-sandbox','--disable-dev-shm-usage']});
 try{
  const page=await browser.newPage({viewport:{width:480,height:320}}),errors=[],failed=[],writes=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(/Failed to load|initialization failed/.test(m.text()))failed.push(m.text())});
  await page.route('**/*',async r=>{if(!['GET','HEAD'].includes(r.request().method())){writes.push(r.request().url());await r.abort();return;}const u=new URL(r.request().url());if(candidate&&u.origin===new URL(base).origin&&u.pathname.endsWith('/world.json')){const response=await r.fetch();await r.fulfill({response,json:expected});return;}await r.continue();});
  const start=performance.now();await page.goto(base+'?capture=1&theta=155&z=-9&yaw=90&pitch=0',{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__oneillSimReady||window.__oneillSimError,null,{timeout:180000}).catch(async error=>{console.log(JSON.stringify({startupTimeout:true,errors,failed,writes,state:await page.evaluate(()=>({ready:window.__oneillSimReady,error:window.__oneillSimError,overlay:document.querySelector('#overlay')?.textContent,resources:performance.getEntriesByType('resource').slice(-12).map(r=>r.name)})).catch(e=>String(e))}));throw error;});
  const startupMs=performance.now()-start;
  await page.evaluate(()=>{window.requestAnimationFrame=()=>0;});await page.setViewportSize({width:960,height:600});
  const result=await page.evaluate(async()=>{
   if(window.__oneillSimError)throw Error(window.__oneillSimError);window.requestAnimationFrame=()=>0;
   const {scene,renderer,camera,habitatGroup}=await import('./src/scene.js'),{editorState,exportWorldState}=await import('./src/editor/state.js'),{characterColliders}=await import('./src/physics/collider-world.js');habitatGroup.updateWorldMatrix(true,true);
   const roots=habitatGroup.children.filter(o=>o.userData.assetId),meshes=[],batch=habitatGroup.children.find(g=>g.name==='settlement-render-batches');batch?.traverse(o=>{if(o.isInstancedMesh)meshes.push(o)});
   const rows=roots.map(o=>{let decoded=true,triangleCount=0;o.traverse(c=>{if(!c.isMesh)return;triangleCount+=(c.geometry.index?.count||c.geometry.attributes.position.count)/3;for(const m of Array.isArray(c.material)?c.material:[c.material])if(m.map&&!m.map.image?.width)decoded=false});return {id:o.userData.assetId,decoded,triangleCount,collision:characterColliders.colliders.get(o.userData.assetId)?.length||0,scale:o.scale.toArray()}});
   renderer.render(scene,camera);return {savedIds:editorState.placedAssets.map(a=>a.id),sceneIds:rows.map(r=>r.id),rows,exported:exportWorldState(),colliders:characterColliders.colliders.size,triangles:characterColliders.triangleCount,batches:meshes.length,batchedInstances:meshes.reduce((n,m)=>n+m.count,0),render:{...renderer.info.render},circulation:window.__oneillSettlement.circulation.stats,diagnostics:window.__oneillSettlement.circulation.plan.diagnostics,landmarks:window.__oneillSettlementTour.landmarks.length,atlasRequests:performance.getEntriesByType('resource').filter(r=>r.name.includes('TorusSettlementFarm_Atlas.png')).length};
  });
  assert.deepEqual(result.savedIds,expected.assets.map(a=>a[0]));assert.deepEqual(result.sceneIds,expected.assets.map(a=>a[0]));assert.equal(result.rows.length,expected.assets.length);assert.equal(result.landmarks,expected.settlementDesign.landmarks.length);assert.deepEqual(result.exported.settlementDesign,expected.settlementDesign);assert.deepEqual(result.exported.terraces,expected.terraces);assert.deepEqual(result.exported.masterPlan,expected.masterPlan);
  assert.deepEqual(result.exported.assets.map(a=>[a[0],result.exported.assetTypes[a[1]],...a.slice(2)]),expected.assets.map(a=>[a[0],expected.assetTypes[a[1]],...a.slice(2)]));
  for(const r of result.rows){assert.equal(r.decoded,true,'Undecoded texture '+r.id);assert.ok(r.triangleCount>0);const row=expected.assets.find(a=>a[0]===r.id);if(row[7]?.worldTransform||row[7]?.collisionMode==='none')assert.equal(r.collision,0,r.id);else assert.ok(r.collision>0,r.id+' lacks collision');}
  assert.ok(result.batches>0&&result.batchedInstances>500,'Dense scene must actually instance');assert.ok(result.atlasRequests>0&&result.atlasRequests<=3,'Farm atlas not pooled');assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);assert.deepEqual(writes,[]);
  const views=[];
  const landmarkIds=['settlement-neighborhood-b-landmark-center','settlement-neighborhood-b-landmark-park-3','settlement-neighborhood-c-landmark-center','settlement-residential-a-residential-a-49-garden','settlement-residential-a-residential-a-96-room','settlement-farm-b-precinct','settlement-farm-c-precinct'];
  for(const id of landmarkIds){
   const view=await page.evaluate(async id=>{const T=await import('three'),{scene,renderer,camera}=await import('./src/scene.js'),{humanController,updateHumanMode}=await import('./src/controls/modes/human.js');const p=window.__oneillSettlementTour.visit(id);for(let i=0;i<120;i++)updateHumanMode(1/120);renderer.render(scene,camera);return {id,name:p.name,position:humanController.position.toArray(),grounded:humanController.grounded,clear:humanController.clear(),render:{...renderer.info.render}};},id);
   assert.equal(view.grounded,true,JSON.stringify(view));assert.equal(view.clear,true,JSON.stringify(view));views.push(view);await page.screenshot({path:path.join(scratch,id+'-human.png')});
   await page.evaluate(async id=>{const T=await import('three'),{scene,renderer,habitatGroup}=await import('./src/scene.js'),p=window.__oneillSettlementTour.landmarks.find(p=>p.id===id),r=830-p.height,c=new T.PerspectiveCamera(58,960/600,.05,5000);c.position.copy(habitatGroup.localToWorld(new T.Vector3((r-28)*Math.cos(p.theta),(r-28)*Math.sin(p.theta),p.z+65)));c.up.copy(new T.Vector3(-Math.cos(p.theta),-Math.sin(p.theta),0).transformDirection(habitatGroup.matrixWorld));c.lookAt(habitatGroup.localToWorld(new T.Vector3(r*Math.cos(p.theta),r*Math.sin(p.theta),p.z)));renderer.render(scene,c);},id);await page.screenshot({path:path.join(scratch,id+'-overview.png')});
  }
  await page.setViewportSize({width:480,height:320});await page.goto(base,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__oneillSimReady||window.__oneillSimError,null,{timeout:180000});
  const initial=await page.evaluate(()=>{window.requestAnimationFrame=()=>0;return {error:window.__oneillSimError,id:window.__oneillSettlementVisit?.id}});assert.equal(initial.error,undefined);assert.equal(initial.id,'settlement-residential-a-residential-a-49-garden','Bare root must start at the reviewed garden basin');
  await page.locator('#settlement-tour summary').click();await page.locator('#settlement-tour select').selectOption('settlement-neighborhood-b-landmark-center');await page.locator('#settlement-tour button').click();assert.equal(await page.evaluate(()=>window.__oneillSettlementVisit.id),'settlement-neighborhood-b-landmark-center');
  assert.deepEqual(errors,[]);assert.deepEqual(writes,[]);result.views=views;result.startupMs=startupMs;result.readinessMs=performance.now()-start;await fs.writeFile(path.join(scratch,'settlement-design-profile.json'),JSON.stringify(result,null,2));console.log(JSON.stringify({settlement:{candidate,records:result.rows.length,batches:result.batches,batchedInstances:result.batchedInstances,colliders:result.colliders,triangles:result.triangles,atlasRequests:result.atlasRequests,diagnosticCount:result.diagnostics.length,views:views.map(v=>({name:v.name,calls:v.render.calls,triangles:v.render.triangles})),startupMs,readinessAndReviewMs:result.readinessMs,defaultTourAndControls:true}}));
 }finally{await browser.close();}
});
