import Link from 'next/link';
import {farmAllocations,farmDecks,farmBlocks,farmArea,farmStart,farmEnd} from '../../src/agriculture-plan.js';
import FarmPlan from './plan';
import '../residential/residential.css';
import './agriculture.css';
export const metadata={title:'Agricultural terraces · Stanford Torus'};
const n=v=>v.toLocaleString('en',{maximumFractionDigits:1});
export default function Agriculture(){return <main className="residential-page agriculture-page">
<nav><a href="/oneillsim/?theta=60.2&z=0&mode=planner&height=35&pitch=-20&yaw=-90">Open farm in 3D ↗</a><Link href="/residential/">Residential plan</Link><Link href="/assets/">Assets</Link><Link href="/study/">Study</Link></nav>
<header><p className="eyebrow">DESIGN NOTE 02 · TERRACED FARM BLOCKOUT</p><h1>One farm, seven levels.</h1><p>Farm A occupies the next 60° sector, from 60° to 120°. It supplies one-third of a 10,000-person colony: 147,333 m² of crops, 17,000 m² of animal areas, plus drying, food handling and water treatment.</p></header>
<FarmPlan/>
<section><h2>The drawings we are following</h2><div className="farm-references"><Link href="/study/#figure-5-11"><img src="/oneillsim/study/images/sp413-p0114-00.jpg" alt="NASA Figure 5-11: overlapping agricultural terraces"/><span>Figure 5-11 · overlooking the farms</span></Link><Link href="/study/#figure-5-12"><img src="/oneillsim/study/images/sp413-p0114-02.jpg" alt="NASA Figure 5-12: agricultural decks inside the lower tube arc"/><span>Figure 5-12 · the lower arc of the tube</span></Link></div><p>Both drawings were checked against PDF page 114 (printed page 97). The section identifies ponds/rice, grain, vegetables/soybeans/corn, sorghum/forage/animals, drying/grain storage, meat processing, and waste treatment/pumping. It is a schematic, not a dimensioned deck plan. Our seven elevations and widths are authored to fit within the 65 m tube radius.</p></section>
<section><h2>Area ledger: one-third of the colony</h2><p>The detailed <Link href="/study/#sp413-s02395">plant table 5-4</Link> and <Link href="/study/#sp413-s02393">animal table 5-5</Link> were visually checked against <a href="https://ntrs.nasa.gov/api/citations/19770014162/downloads/19770014162.pdf#page=115">the original scan, PDF page 115</a>. Every amount below is represented by colored plots; animals are pen or tank allocations, not thousands of individual meshes. The factor is exactly 10,000 ÷ 3, avoiding cumulative rounding between farms.</p><div className="table-scroll"><table><thead><tr><th>Use</th><th>m²/person</th><th>Target m²/farm</th><th>Placed m²</th><th>Reference</th></tr></thead><tbody>{farmAllocations.map((a,i)=><tr key={a.id}><th><i className="swatch" style={{background:a.color}}/>{a.name}</th><td>{a.perPerson}</td><td>{n(a.area)}</td><td>{n(farmArea(a.id))}</td><td>{i<6?'Table 5-4':i<10?'Table 5-5':'Table 3-2'}</td></tr>)}</tbody></table></div><p>Total food-production allocation: <strong>204,333 m² per farm</strong> (61.3 m²/person). Water treatment adds 13,333 m², for <strong>217,667 m² placed</strong>. Treatment is part of the mechanical budget, not an extra crop requirement. Table 3-2’s 44 and 5 m²/person crop/animal allowances are rounded; the detailed tables give 44.2 and 5.1, explaining the 0.3 m²/person difference from its 61 m² agricultural total. Crop soil depth is 0.3 m in the prose; plot heights here are visual placeholders, not soil specifications.</p></section>
<section><h2>Deck capacity and overlap</h2><div className="table-scroll"><table><thead><tr><th>Deck</th><th>Elevation m</th><th>Total band width m</th><th>Gross deck m²</th><th>Placed use m²</th></tr></thead><tbody>{farmDecks.map(d=>{const width=d.bands.reduce((s,[a,b])=>s+b-a,0);return <tr key={d.id}><th>{d.name}</th><td>{d.height}</td><td>{width}</td><td>{n(width*(830-d.height)*(farmEnd-farmStart))}</td><td>{n(farmBlocks.filter(b=>b.deckId===d.id).reduce((s,b)=>s+b.area,0))}</td></tr>})}</tbody></table></div><p>Gross area is before stair openings; unused area is access and unassigned reserve, not additional crop credit. Length uses the radius of each deck: outward, lower decks are longer than the ground sheet. Widths and a 0.4 m slab fit inside the tube cross-section. The first four decks are 15 m apart; service decks below have 10, 6 and 5 m spacing. These are our choices, not measured dimensions from the illustration.</p><p>The shelves widen toward the middle, then narrow to fit the bottom arc. Some plots are covered by higher shelves. Lighting, transparent pond bottoms, irrigation cascades, enclosure partitions, drainage and structure have not been modeled or validated. This layout proves area placement, not crop productivity or a sunlight solution.</p></section>
<section><h2>Placement and walking</h2><p>The ground sheet is opened only in this agricultural sector. Decks have stable IDs, elevations and footprints saved in the world. Select a level in the simulation to isolate it; editor picking, previews and newly placed assets use that deck’s height. Saving retains the attachment. Base-ground texture brushes do not paint decks.</p><p>Six 4 m-wide stair runs connect consecutive levels near the sector entrance. Visible treads use roughly 0.15 m rises, with a continuous walking surface underneath so the camera does not judder at each step. “Walk this deck” places you on a clear side margin; select All levels to see the overlapping farm. Stairs lie within the first 40 m of the sector, before the plots begin at 50 m.</p><p>Walking follows deck and stair height and blocks unsupported edge crossings. This is an initial walking implementation: no full building collision, railings, ceiling collision, accessible lifts, fire-escape design or cargo transport yet. The farm’s +5 m entry shelf is not yet connected to the residential ground by a bridge; use the deck entry buttons for now.</p></section>
<section><h2>Decisions and open questions</h2><ul><li>The colony has three farms with the same crop mix and staggered harvests (<Link href="/study/#sp413-s02357">Chapter 5</Link>). Farm A is the only one populated in this iteration.</li><li>Soybeans dominate: 78,333 m² per farm, split between the vegetable and lower growing decks. The diagram’s lower sorghum/forage label is guidance, not a measured plot allocation; our sorghum is on the grain terraces. Cattle use plant roughage, per the table note. Extra forage area has not been invented.</li><li>Fish stay on the upper shelf; grain below; vegetables and beans on the next shelves; animals on the lower growing deck. Drying, processing/storage, and treatment descend below them. Food collection and grain storage share the 4 m²/person handling allowance; we have not counted storage twice.</li><li>Table 5-5 implies about 86,667 fish, 20,667 chickens, 9,333 rabbits and 500 cattle per farm. The tour rounds these to about 90,000 / 20,000 / 10,000 / 500. Pen areas use the printed area/person column, whose rounding differs slightly from multiplying count by area/animal.</li><li>Fruit is supplied by residential trees, as noted below table 5-4. Alfalfa appears in the tour but has no separate allocation in that table; it remains an unresolved crop-program detail.</li><li>Equal 60° sectors remain a simulator convention. This stacked farm fits its area program, but does not settle the residential sector shortfall or prove that our division matches the original master plan.</li></ul></section>
</main>}
