'use client';
import {useState} from 'react';
import {farmDecks,farmBlocks,farmStart,farmEnd,farmStairs} from '../../src/agriculture-plan.js';
export default function FarmPlan(){
 const [id,setId]=useState(farmDecks[0].id),[plot,setPlot]=useState(null);
 const deck=farmDecks.find(d=>d.id===id),length=(farmEnd-farmStart)*(830-deck.height);
 return <section><h2>Terraces inside the tube</h2><p>Choose a level in the section or menu. Elevations are relative to the residential ground sheet; negative is outward, toward the bottom of the tube.</p>
 <div className="farm-diagrams"><svg viewBox="-75 -72 150 145" aria-label="Agricultural cross-section" className="cross-section"><circle r="65" fill="#eef1e8" stroke="#8c9a8c" strokeWidth=".7"/><line x1="-65" y1="0" x2="65" y2="0" stroke="#9ca59c" strokeDasharray="2 2" strokeWidth=".3"/>{farmDecks.map(d=><g key={d.id} role="button" tabIndex={0} aria-label={d.name} onClick={()=>{setId(d.id);setPlot(null)}} onKeyDown={e=>{if(e.key==='Enter'){setId(d.id);setPlot(null)}}}><title>{`${d.name}: ${d.height} m`}</title>{d.bands.map(([a,b])=><rect key={a} x={a} y={-d.height} width={b-a} height="1.5" fill={d.id===id?'#b77b31':'#546f5b'}/>)}</g>)}<text x="0" y="-57" textAnchor="middle" fontSize="5">130 m tube diameter</text></svg>
 <div><label>Selected deck <select value={id} onChange={e=>{setId(e.target.value);setPlot(null)}}>{farmDecks.map(d=><option value={d.id} key={d.id}>{d.name} · {d.height} m</option>)}</select></label><p><a href={`/oneillsim/?theta=${(farmStart+farmEnd)/2*180/Math.PI}&z=0&mode=planner&height=180&pitch=-89&yaw=0&deck=${id}`}>Inspect this deck in 3D ↗</a></p><p><a href={`/oneillsim/?theta=${farmStart*180/Math.PI+2}&z=0&mode=human&deck=${id}`}>Walk this deck ↗</a></p><p>Deck isolation reveals areas covered by the level above. The 3D selector also chooses the surface for editor placement.</p></div></div>
 <svg viewBox={`0 -68 ${length} 136`} className="district-map" aria-label="Selected agricultural deck plan">{deck.bands.map(([a,b])=><rect key={a} x="0" y={a} width={length} height={b-a} fill="#d9ded2"/>)}{farmStairs.filter(s=>s.upper===id).map(s=><rect key={s.id} x={(s.start-farmStart)*(830-deck.height)} y={s.z-s.width/2} width={(s.end-s.start)*(830-deck.height)} height={s.width} fill="#b8873d"><title>Stairs to the next deck</title></rect>)}{farmBlocks.filter(b=>b.deckId===id).map(b=><g key={b.id} tabIndex={0} role="button" aria-label={b.name} onClick={()=>setPlot(b)} onKeyDown={e=>{if(e.key==='Enter')setPlot(b)}}><title>{`${b.name}: ${b.area.toFixed(0)} m²`}</title><rect x={(b.theta-farmStart)*(830-deck.height)-b.width/2} y={b.z-b.depth/2} width={b.width} height={b.depth} fill={b.color} stroke="white" strokeWidth=".35"/></g>)}</svg>
 <p className="selection">{plot?`${plot.name}: ${plot.width.toFixed(2)} × ${plot.depth.toFixed(2)} m; ${plot.area.toLocaleString('en',{maximumFractionDigits:1})} m². All plot dimensions are actual deck-level dimensions.`:'Click a colored plot to inspect it. The first 50 m is reserved for access and stairs; narrow margins run alongside each planting band. Ochre marks the stairs to the next deck.'}</p></section>
}
